version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51786:51773
      - 52786:52773
      - 53786:53773
    volumes:
      - ./:/irisdev/app